#!/bin/bash

FUDDIR="$HOME/.fud"

# Print on screen
printScreen() { echo -e "$@"; }

printScreen "Questo script configurerà fud tramite domande interattive."
printScreen -n "Procedere? (Y/n): "
read sure
if [[ $sure = "Y" || $sure = "y" ]]; then
	# Crea la cartella di Fud
	mkdir -p $FUDDIR
	printScreen "Creata la cartella $FUDDIR"
	# Crea il file di configurazione e il file di log
	touch $FUDDIR/fud.conf
	printScreen "Creato il file $FUDDIR/fud.conf"
	touch $FUDDIR/fud.log
	printScreen "Creato il file $FUDDIR/fud.log"
	# Aggiunge l'utente al gruppo fuse
	#newgrp fuse
	#printScreen "Aggiunto l'utente $USERNAME al gruppo fuse"
	
	printScreen
	printScreen "Scegli il metodo da utilizzare per la sincronizzazione."
	printScreen "[1] ssh tramite sshfs"
	printScreen "[2] ftp tramite curlftpfs"
	printScreen -n "Metodo: "
	read method

else
	exit 0;
fi

