#!/bin/bash

# Fud Dependencies
DEPENDENCIES=(curlftpfs inotify-tools libnotify-bin nfs-common sshfs unison sudo)

#Colors
RED="\e[1;31m" #Red
GREEN="\e[1;32m" #Green
YELLOW="\e[1;33m" #Yellow
RESET="\e[0m" #Reset!

# Print on screen
printScreen() { echo -e "$@"; }

# Check if user is root
if [[ $EUID -ne 0 ]]; then
   printScreen $RED"Error:"$RESET" this script must be run as root."
   exit 1
fi

# $F is the directory where this script is located
F=$(dirname $(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}"))
# Copy executables files in /usr/local/bin and set execute permissions
cp $F/fud $F/fudconf /usr/local/bin
chmod +x /usr/local/bin/fud /usr/local/bin/fudconf
# Copy Fud icon in /usr/share/app-install/icons/
cp $F/fud.png /usr/share/app-install/icons/

# Change, if necessary, /etc/fuse.conf file
if grep "user_allow_other" /etc/fuse.conf &> /dev/null; then
	sed -i "s/#user_allow_other/user_allow_other/g" /etc/fuse.conf
else
	echo "user_allow_other" >> /etc/fuse.conf
fi

# What dependencies are missing?
PKGSTOINSTALL=""
for (( i=0; i<${tLen=${#DEPENDENCIES[@]}}; i++ )); do
	# Debian, Ubuntu and derivatives (with dpkg)
	if which dpkg &> /dev/null; then
		if [[ ! `dpkg -l | grep -w "ii  ${DEPENDENCIES[$i]} "` ]]; then
			PKGSTOINSTALL=$PKGSTOINSTALL" "${DEPENDENCIES[$i]}
		fi
	# OpenSuse, Mandriva, Fedora, CentOs, ecc. (with rpm)
	elif which rpm &> /dev/null; then
		if [[ ! `rpm -q ${DEPENDENCIES[$i]}` ]]; then
			PKGSTOINSTALL=$PKGSTOINSTALL" "${DEPENDENCIES[$i]}
		fi
	# ArchLinux (with pacman)
	elif which pacman &> /dev/null; then
		if [[ ! `pacman -Qqe | grep "${DEPENDENCIES[$i]}"` ]]; then
			PKGSTOINSTALL=$PKGSTOINSTALL" "${DEPENDENCIES[$i]}
		fi
	# If it's impossible to determine if there are missing dependencies, mark all as missing
	else
		PKGSTOINSTALL=$PKGSTOINSTALL" "${DEPENDENCIES[$i]}
	fi
done

# If some dependencies are missing, asks if user wants to install
if [ "$PKGSTOINSTALL" != "" ]; then
	printScreen -n "Some dependencies are missing. Want to install them? (Y/n): "
	read SURE
	# If user wanna install missing dependencies
	if [[ $SURE = "Y" || $SURE = "y" || $SURE = "" ]]; then	
		# Debian, Ubuntu and derivatives (with apt-get)
		if which apt-get &> /dev/null; then
			apt-get install $PKGSTOINSTALL
		# OpenSuse (with zypper)
		elif which zypper &> /dev/null; then
			zypper in $PKGSTOINSTALL
		# Mandriva (with urpmi)
		elif which urpmi &> /dev/null; then
			urpmi $PKGSTOINSTALL
		# Fedora and CentOS (with yum)
		elif which yum &> /dev/null; then
			yum install $PKGSTOINSTALL
		# ArchLinux (with pacman)
		elif which pacman &> /dev/null; then
			pacman -Sy $PKGSTOINSTALL
		# Else, if no package manager has been founded
		else
			# Set $NOPKGMANAGER
			NOPKGMANAGER=TRUE
			printScreen $RED"ERROR:"$RESET": impossible to found a package manager in your sistem. Please, install manually ${DEPENDENCIES[*]}."
		fi
		# Check if installation is successful
		if [[ $? -eq 0 && ! -z $NOPKGMANAGER ]] ; then
			printScreen "All dependencies are satisfied."
		# Else, if installation isn't successful		
		else
			printScreen $RED"ERROR:"$RESET": impossible to install some missing dependencies. Please, install manually ${DEPENDENCIES[*]}."
		fi
	# Else, if user don't wanna install missing dependencies
	else
		printScreen $YELLOW"WARNING:"$RESET": Some dependencies may be missing. So, please, install manually ${DEPENDENCIES[*]}."
	fi
fi

# Set sudo permissions for group fuse
# Users members of group fuse will be able to mount, umount and edit /etc/fstab
# ;)
if ! egrep -i "^fuse" /etc/group > /dev/null; then
	addgroup fuse
fi
echo "Cmnd_Alias FUD = /bin/mount, /bin/umount, /usr/bin/tee, /bin/sed" >> /etc/sudoers
echo "%fuse ALL=NOPASSWD:FUD" >> /etc/sudoers
echo "ALL ALL=(ALL) NOPASSWD: /usr/sbin/adduser" >> /etc/sudoers

printScreen $GREEN"Success"$RESET": Fud has been properly installed."

exit 0
